# Generated by Django 5.1.7 on 2025-03-26 06:13

import aiinterview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiinterview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=aiinterview.models.user_directory_path),
        ),
    ]
