# Generated by Django 5.1.7 on 2025-03-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiinterview', '0002_interview_resume_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
